[platformio]
src_dir = .
default_envs = esp32-c3-devkitm-1

[env:esp32-c3-devkitm-1]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200
monitor_dtr = 0
monitor_rts = 0
extra_scripts = pre:tools/platformio_config.py
build_flags =
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1

[env:esp32-c3-ota]
extends = env:esp32-c3-devkitm-1
upload_protocol = espota
upload_port = jvdp-lightsensor.local
upload_flags =
    --auth=${sysenv.JVDP_OTA_PASSWORD}
